# Generated by Django 2.1.2 on 2019-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CASLPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject', max_length=128)),
                ('action', models.TextField(help_text='Action', max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='caslpermission',
            unique_together={('subject', 'action')},
        ),
    ]
